package com.wang.social.im.view.emotion;

import com.wang.social.im.R.drawable;

public class DefEmoticons {
    public static final EmojiBean[] sEmojiArray;
    public static final EmojiBean[] sFaceArray;
    public static final EmojiBean[] sFaceTwoArray;

    public DefEmoticons() {
    }

    static {
        sEmojiArray = new EmojiBean[]{
                new EmojiBean(drawable.emoji_0x1f604, EmojiParse.fromCodePoint(128516)),
                new EmojiBean(drawable.emoji_0x1f603, EmojiParse.fromCodePoint(128515)),
                new EmojiBean(drawable.emoji_0x1f60a, EmojiParse.fromCodePoint(128522)),
                new EmojiBean(drawable.emoji_0x1f609, EmojiParse.fromCodePoint(128521)),
                new EmojiBean(drawable.emoji_0x1f60d, EmojiParse.fromCodePoint(128525)),
                new EmojiBean(drawable.emoji_0x1f618, EmojiParse.fromCodePoint(128536)),
                new EmojiBean(drawable.emoji_0x1f61a, EmojiParse.fromCodePoint(128538)),
                new EmojiBean(drawable.emoji_0x1f61c, EmojiParse.fromCodePoint(128540)),
                new EmojiBean(drawable.emoji_0x1f61d, EmojiParse.fromCodePoint(128541)),
                new EmojiBean(drawable.emoji_0x1f633, EmojiParse.fromCodePoint(128563)),
                new EmojiBean(drawable.emoji_0x1f601, EmojiParse.fromCodePoint(128513)),
                new EmojiBean(drawable.emoji_0x1f614, EmojiParse.fromCodePoint(128532)),
                new EmojiBean(drawable.emoji_0x1f60c, EmojiParse.fromCodePoint(128524)),
                new EmojiBean(drawable.emoji_0x1f612, EmojiParse.fromCodePoint(128530)),
                new EmojiBean(drawable.emoji_0x1f61e, EmojiParse.fromCodePoint(128542)),
                new EmojiBean(drawable.emoji_0x1f623, EmojiParse.fromCodePoint(128547)),
                new EmojiBean(drawable.emoji_0x1f622, EmojiParse.fromCodePoint(128546)),
                new EmojiBean(drawable.emoji_0x1f602, EmojiParse.fromCodePoint(128514)),
                new EmojiBean(drawable.emoji_0x1f62d, EmojiParse.fromCodePoint(128557)),
                new EmojiBean(drawable.emoji_0x1f62a, EmojiParse.fromCodePoint(128554)),
                new EmojiBean(drawable.emoji_0x1f625, EmojiParse.fromCodePoint(128549)),
                new EmojiBean(drawable.emoji_0x1f630, EmojiParse.fromCodePoint(128560)),
                new EmojiBean(drawable.emoji_0x1f613, EmojiParse.fromCodePoint(128531)),
                new EmojiBean(drawable.emoji_0x1f628, EmojiParse.fromCodePoint(128552)),
                new EmojiBean(drawable.emoji_0x1f631, EmojiParse.fromCodePoint(128561)),
                new EmojiBean(drawable.emoji_0x1f620, EmojiParse.fromCodePoint(128544)),
                new EmojiBean(drawable.emoji_0x1f621, EmojiParse.fromCodePoint(128545)),
                new EmojiBean(drawable.emoji_0x1f616, EmojiParse.fromCodePoint(128534)),
                new EmojiBean(drawable.emoji_0x1f637, EmojiParse.fromCodePoint(128567)),
                new EmojiBean(drawable.emoji_0x1f632, EmojiParse.fromCodePoint(128562)),
                new EmojiBean(drawable.emoji_0x1f47f, EmojiParse.fromCodePoint(128127)),
                new EmojiBean(drawable.emoji_0x1f60f, EmojiParse.fromCodePoint(128527)),
                new EmojiBean(drawable.emoji_0x1f466, EmojiParse.fromCodePoint(128102)),
                new EmojiBean(drawable.emoji_0x1f467, EmojiParse.fromCodePoint(128103)),
                new EmojiBean(drawable.emoji_0x1f468, EmojiParse.fromCodePoint(128104)),
                new EmojiBean(drawable.emoji_0x1f469, EmojiParse.fromCodePoint(128105)),
                new EmojiBean(drawable.emoji_0x1f31f, EmojiParse.fromCodePoint(127775)),
                new EmojiBean(drawable.emoji_0x1f444, EmojiParse.fromCodePoint(128068)),
                new EmojiBean(drawable.emoji_0x1f44d, EmojiParse.fromCodePoint(128077)),
                new EmojiBean(drawable.emoji_0x1f44e, EmojiParse.fromCodePoint(128078)),
                new EmojiBean(drawable.emoji_0x1f44c, EmojiParse.fromCodePoint(128076)),
                new EmojiBean(drawable.emoji_0x1f44a, EmojiParse.fromCodePoint(128074)),
                new EmojiBean(drawable.emoji_0x270a, EmojiParse.fromChar('✊')),
                new EmojiBean(drawable.emoji_0x270c, EmojiParse.fromChar('✌')),
                new EmojiBean(drawable.emoji_0x1f446, EmojiParse.fromCodePoint(128070)),
                new EmojiBean(drawable.emoji_0x1f447, EmojiParse.fromCodePoint(128071)),
                new EmojiBean(drawable.emoji_0x1f449, EmojiParse.fromCodePoint(128073)),
                new EmojiBean(drawable.emoji_0x1f448, EmojiParse.fromCodePoint(128072)),
                new EmojiBean(drawable.emoji_0x1f64f, EmojiParse.fromCodePoint(128591)),
                new EmojiBean(drawable.emoji_0x1f44f, EmojiParse.fromCodePoint(128079)),
                new EmojiBean(drawable.emoji_0x1f4aa, EmojiParse.fromCodePoint(128170)),
                new EmojiBean(drawable.emoji_0x1f457, EmojiParse.fromCodePoint(128087)),
                new EmojiBean(drawable.emoji_0x1f380, EmojiParse.fromCodePoint(127872)),
                new EmojiBean(drawable.emoji_0x2764, EmojiParse.fromChar('❤')),
                new EmojiBean(drawable.emoji_0x1f494, EmojiParse.fromCodePoint(128148)),
                new EmojiBean(drawable.emoji_0x1f48e, EmojiParse.fromCodePoint(128142)),
                new EmojiBean(drawable.emoji_0x1f436, EmojiParse.fromCodePoint(128054)),
                new EmojiBean(drawable.emoji_0x1f431, EmojiParse.fromCodePoint(128049)),
                new EmojiBean(drawable.emoji_0x1f339, EmojiParse.fromCodePoint(127801)),
                new EmojiBean(drawable.emoji_0x1f33b, EmojiParse.fromCodePoint(127803)),
                new EmojiBean(drawable.emoji_0x1f341, EmojiParse.fromCodePoint(127809)),
                new EmojiBean(drawable.emoji_0x1f343, EmojiParse.fromCodePoint(127811)),
                new EmojiBean(drawable.emoji_0x1f319, EmojiParse.fromCodePoint(127769)),
                new EmojiBean(drawable.emoji_0x2600, EmojiParse.fromChar('☀')),
                new EmojiBean(drawable.emoji_0x2601, EmojiParse.fromChar('☁')),
                new EmojiBean(drawable.emoji_0x26a1, EmojiParse.fromChar('⚡')),
                new EmojiBean(drawable.emoji_0x2614, EmojiParse.fromChar('☔')),
                new EmojiBean(drawable.emoji_0x1f47b, EmojiParse.fromCodePoint(128123)),
                new EmojiBean(drawable.emoji_0x1f385, EmojiParse.fromCodePoint(127877)),
                new EmojiBean(drawable.emoji_0x1f381, EmojiParse.fromCodePoint(127873)),
                new EmojiBean(drawable.emoji_0x1f4f1, EmojiParse.fromCodePoint(128241)),
                new EmojiBean(drawable.emoji_0x1f50d, EmojiParse.fromCodePoint(128269)),
                new EmojiBean(drawable.emoji_0x1f4a3, EmojiParse.fromCodePoint(128163)),
                new EmojiBean(drawable.emoji_0x26bd, EmojiParse.fromChar('⚽')),
                new EmojiBean(drawable.emoji_0x2615, EmojiParse.fromChar('☕')),
                new EmojiBean(drawable.emoji_0x1f37a, EmojiParse.fromCodePoint(127866)),
                new EmojiBean(drawable.emoji_0x1f382, EmojiParse.fromCodePoint(127874)),
                new EmojiBean(drawable.emoji_0x1f3e0, EmojiParse.fromCodePoint(127968)),
                new EmojiBean(drawable.emoji_0x1f697, EmojiParse.fromCodePoint(128663)),
                new EmojiBean(drawable.emoji_0x1f559, EmojiParse.fromCodePoint(128345))};

        sFaceArray = new EmojiBean[]{
                new EmojiBean(drawable.im_ww_emoji_001, "1"),
                new EmojiBean(drawable.im_ww_emoji_002, "2"),
                new EmojiBean(drawable.im_ww_emoji_003, "3"),
                new EmojiBean(drawable.im_ww_emoji_004, "4"),
                new EmojiBean(drawable.im_ww_emoji_005, "5"),
                new EmojiBean(drawable.im_ww_emoji_006, "6"),
                new EmojiBean(drawable.im_ww_emoji_007, "7"),
                new EmojiBean(drawable.im_ww_emoji_008, "8"),
                new EmojiBean(drawable.im_ww_emoji_009, "9"),
                new EmojiBean(drawable.im_ww_emoji_010, "10"),
                new EmojiBean(drawable.im_ww_emoji_011, "11"),
                new EmojiBean(drawable.im_ww_emoji_012, "12"),
                new EmojiBean(drawable.im_ww_emoji_013, "13"),
                new EmojiBean(drawable.im_ww_emoji_014, "14"),
                new EmojiBean(drawable.im_ww_emoji_015, "15"),
                new EmojiBean(drawable.im_ww_emoji_016, "16"),
                new EmojiBean(drawable.im_ww_emoji_017, "17"),
                new EmojiBean(drawable.im_ww_emoji_018, "18"),
                new EmojiBean(drawable.im_ww_emoji_019, "19"),
                new EmojiBean(drawable.im_ww_emoji_020, "20"),
                new EmojiBean(drawable.im_ww_emoji_021, "21"),
                new EmojiBean(drawable.im_ww_emoji_022, "22"),
                new EmojiBean(drawable.im_ww_emoji_023, "23"),
                new EmojiBean(drawable.im_ww_emoji_024, "24"),
                new EmojiBean(drawable.im_ww_emoji_025, "25"),
                new EmojiBean(drawable.im_ww_emoji_026, "26"),
                new EmojiBean(drawable.im_ww_emoji_027, "27"),
                new EmojiBean(drawable.im_ww_emoji_028, "28"),
                new EmojiBean(drawable.im_ww_emoji_029, "29"),
                new EmojiBean(drawable.im_ww_emoji_030, "30"),
                new EmojiBean(drawable.im_ww_emoji_031, "31"),
                new EmojiBean(drawable.im_ww_emoji_032, "32"),
                new EmojiBean(drawable.im_ww_emoji_033, "33"),
                new EmojiBean(drawable.im_ww_emoji_034, "34"),
                new EmojiBean(drawable.im_ww_emoji_035, "35"),
                new EmojiBean(drawable.im_ww_emoji_036, "36"),
                new EmojiBean(drawable.im_ww_emoji_037, "37"),
                new EmojiBean(drawable.im_ww_emoji_038, "38"),
                new EmojiBean(drawable.im_ww_emoji_039, "39"),
                new EmojiBean(drawable.im_ww_emoji_040, "40"),
                new EmojiBean(drawable.im_ww_emoji_041, "41"),
                new EmojiBean(drawable.im_ww_emoji_042, "42"),
                new EmojiBean(drawable.im_ww_emoji_043, "43"),
                new EmojiBean(drawable.im_ww_emoji_044, "44"),
                new EmojiBean(drawable.im_ww_emoji_045, "45"),
                new EmojiBean(drawable.im_ww_emoji_046, "46"),
                new EmojiBean(drawable.im_ww_emoji_047, "47"),
                new EmojiBean(drawable.im_ww_emoji_048, "48"),
                new EmojiBean(drawable.im_ww_emoji_049, "49"),
                new EmojiBean(drawable.im_ww_emoji_050, "50"),
                new EmojiBean(drawable.im_ww_emoji_051, "51"),
                new EmojiBean(drawable.im_ww_emoji_052, "52")};

        sFaceTwoArray = new EmojiBean[]{
                new EmojiBean(drawable.im_ww_emoji_101, "101"),
                new EmojiBean(drawable.im_ww_emoji_102, "102"),
                new EmojiBean(drawable.im_ww_emoji_103, "103"),
                new EmojiBean(drawable.im_ww_emoji_104, "104"),
                new EmojiBean(drawable.im_ww_emoji_105, "105"),
                new EmojiBean(drawable.im_ww_emoji_106, "106"),
                new EmojiBean(drawable.im_ww_emoji_107, "107"),
                new EmojiBean(drawable.im_ww_emoji_108, "108"),
                new EmojiBean(drawable.im_ww_emoji_109, "109"),
                new EmojiBean(drawable.im_ww_emoji_110, "110"),
                new EmojiBean(drawable.im_ww_emoji_111, "111"),
                new EmojiBean(drawable.im_ww_emoji_112, "112"),
                new EmojiBean(drawable.im_ww_emoji_113, "113"),
                new EmojiBean(drawable.im_ww_emoji_114, "114"),
                new EmojiBean(drawable.im_ww_emoji_115, "115"),
                new EmojiBean(drawable.im_ww_emoji_116, "116"),
                new EmojiBean(drawable.im_ww_emoji_117, "117"),
                new EmojiBean(drawable.im_ww_emoji_118, "118"),
                new EmojiBean(drawable.im_ww_emoji_119, "119"),
                new EmojiBean(drawable.im_ww_emoji_120, "120"),
                new EmojiBean(drawable.im_ww_emoji_121, "121"),
                new EmojiBean(drawable.im_ww_emoji_122, "122"),
                new EmojiBean(drawable.im_ww_emoji_123, "123"),
                new EmojiBean(drawable.im_ww_emoji_124, "124")};
    }
}
